Repository brain-tec/account-financial-reporting, pull requests merged in 2019-02, with the labels that each got.

#209 [bt#4251] Offene Posten Liste vs. Saldenbilanz (#4251)
  account_financial_report_webkit/account_move_line.py
Labels: bug

#211 Syncing from upstream OCA/account-financial-reporting (11.0)
  account_financial_report/i18n/de.po
  account_financial_report_date_range/i18n/de.po
Labels: 11.0

#213 [bt#4400] exclude journal "EJ" from counterpartlookup
  account_financial_report_webkit/report/common_reports.py
Labels: 8.0.valaiscom

#214 Syncing from upstream OCA/account-financial-reporting (10.0)
  account_financial_report_qweb/i18n/es.po
  account_financial_report_qweb/wizard/general_ledger_wizard.py
Labels: 10.0
