Repository brain-tec/account-financial-reporting, pull requests merged in 2019-05, with the labels that each got.

#226 Syncing from upstream OCA/account-financial-reporting (12.0)
  account_tax_balance/i18n/fr.po
Labels: 12.0

#227 Syncing from upstream OCA/account-financial-reporting (12.0)
  .travis.yml
  account_tax_balance/tests/test_account_tax_balance.py
Labels: 12.0

#228 Syncing from upstream OCA/account-financial-reporting (10.0)
  account_financial_report_horizontal/i18n/fr.po
  account_financial_report_qweb/i18n/es.po
  account_financial_report_qweb/i18n/fr.po
  account_move_line_report_xls/i18n/fr.po
  customer_outstanding_statement/i18n/da.po
Labels: 10.0

#229 Syncing from upstream OCA/account-financial-reporting (11.0)
  account_financial_report/i18n/es.po
  account_financial_report/i18n/it.po
Labels: 11.0

#230 Syncing from upstream OCA/account-financial-reporting (10.0)
  customer_activity_statement/i18n/da.po
Labels: 10.0

#231 Syncing from upstream OCA/account-financial-reporting (11.0)
  .travis.yml
Labels: 11.0

#232 Syncing from upstream OCA/account-financial-reporting (10.0)
  customer_activity_statement/i18n/da.po
Labels: 10.0

#233 Syncing from upstream OCA/account-financial-reporting (10.0)
  account_financial_report_qweb/i18n/it.po
Labels: 10.0

#234 [bt#4251] revert initial balance mode to default to get
  account_financial_report_webkit/report/partner_balance.py
Labels: 8.0.valaiscom

#235 [bt#4251] revert initial balance mode to default to get
  account_financial_report_webkit/report/partner_balance.py
Labels: 8.0.test.project_va_170

#236 Syncing from upstream OCA/account-financial-reporting (11.0)
  customer_activity_statement/__manifest__.py
  customer_activity_statement/report/customer_activity_statement.py
  customer_outstanding_statement/__manifest__.py
  customer_outstanding_statement/report/customer_outstanding_statement.py
Labels: 11.0

#237 Syncing from upstream OCA/account-financial-reporting (12.0)
  account_tax_balance/__manifest__.py
  account_tax_balance/i18n/account_tax_balance.pot
  account_tax_balance/tests/test_account_tax_balance.py
  account_tax_balance/wizard/open_tax_balances.py
Labels: 12.0

#238 Syncing from upstream OCA/account-financial-reporting (11.0)
  account_financial_report/i18n/account_financial_report.pot
  account_financial_report/i18n/ar.po
  account_financial_report/i18n/ca.po
  account_financial_report/i18n/de.po
  account_financial_report/i18n/es.po
  account_financial_report/i18n/fr.po
  account_financial_report/i18n/hr_HR.po
  account_financial_report/i18n/it.po
  account_financial_report/i18n/nl.po
  account_financial_report/i18n/nl_NL.po
  account_financial_report/i18n/pt.po
  account_financial_report/i18n/ro.po
  account_financial_report/models/account_move_line.py
  account_financial_report/report/open_items.py
  account_financial_report/report/templates/aged_partner_balance.xml
  account_financial_report/report/trial_balance.py
  account_financial_report/static/src/js/account_financial_report_backend.js
  account_financial_report/static/src/js/account_financial_report_widgets.js
  account_financial_report/static/src/less/report.less
  account_financial_report/tests/test_general_ledger.py
  account_financial_report/tests/test_open_items.py
  account_financial_report/tests/test_trial_balance.py
  account_financial_report/view/report_template.xml
  account_financial_report/wizard/aged_partner_balance_wizard.py
  account_financial_report/wizard/general_ledger_wizard.py
  account_financial_report/wizard/general_ledger_wizard_view.xml
  account_financial_report/wizard/open_items_wizard.py
  account_financial_report/wizard/open_items_wizard_view.xml
  account_financial_report/wizard/trial_balance_wizard.py
Labels: 11.0

#239 Syncing from upstream OCA/account-financial-reporting (12.0)
  account_tax_balance/i18n/ca.po
Labels: 12.0

#240 Syncing from upstream OCA/account-financial-reporting (12.0)
  partner_statement/README.rst
  partner_statement/__init__.py
  partner_statement/__manifest__.py
  partner_statement/i18n/ca.po
  partner_statement/i18n/de.po
  partner_statement/i18n/es.po
  partner_statement/i18n/fr.po
  partner_statement/i18n/hr_HR.po
  partner_statement/i18n/it.po
  partner_statement/i18n/nl.po
  partner_statement/i18n/nl_NL.po
  partner_statement/i18n/partner_statement.pot
  partner_statement/i18n/pt.po
  partner_statement/i18n/ro.po
  partner_statement/readme/CONFIGURE.rst
  partner_statement/readme/CONTRIBUTORS.rst
  partner_statement/readme/DESCRIPTION.rst
  partner_statement/readme/HISTORY.rst
  partner_statement/readme/ROADMAP.rst
  partner_statement/readme/USAGE.rst
  partner_statement/report/__init__.py
  partner_statement/report/activity_statement.py
  partner_statement/report/outstanding_statement.py
  partner_statement/report/report_statement_common.py
  partner_statement/security/statement_security.xml
  partner_statement/static/description/icon.png
  partner_statement/static/description/index.html
  partner_statement/static/src/scss/layout_statement.scss
  partner_statement/tests/__init__.py
  partner_statement/tests/test_activity_statement.py
  partner_statement/tests/test_outstanding_statement.py
  partner_statement/tests/test_res_config_settings.py
  partner_statement/views/activity_statement.xml
  partner_statement/views/aging_buckets.xml
  partner_statement/views/assets.xml
  partner_statement/views/outstanding_statement.xml
  partner_statement/views/res_config_settings.xml
  partner_statement/wizard/__init__.py
  partner_statement/wizard/activity_statement_wizard.py
  partner_statement/wizard/outstanding_statement_wizard.py
  partner_statement/wizard/res_config_settings.py
  partner_statement/wizard/statement_common.py
  partner_statement/wizard/statement_wizard.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_statement/odoo/addons/partner_statement
  setup/partner_statement/setup.py
Labels: 12.0

#241 Syncing from upstream OCA/account-financial-reporting (11.0)
  account_financial_report/i18n/account_financial_report.pot
  account_financial_report/i18n/ar.po
  account_financial_report/i18n/ca.po
  account_financial_report/i18n/de.po
  account_financial_report/i18n/es.po
  account_financial_report/i18n/fr.po
  account_financial_report/i18n/hr_HR.po
  account_financial_report/i18n/it.po
  account_financial_report/i18n/nl.po
  account_financial_report/i18n/nl_NL.po
  account_financial_report/i18n/pt.po
  account_financial_report/i18n/ro.po
  account_financial_report/static/src/js/account_financial_report_widgets.js
Labels: 11.0
